# Generated by Django 4.0.6 on 2022-07-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_pimage1_product_pimage2_product_pimage3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pimage1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pimage2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pimage3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pimage4',
        ),
    ]
