# Generated by Django 4.0.6 on 2022-07-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='', upload_to='category'),
            preserve_default=False,
        ),
    ]
